from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, ForeignKey, DateTime, Text, Boolean, JSON, func, Enum
from app.database.base import Base
from datetime import datetime
import enum
from typing import TYPE_CHECKING, Optional, List

if TYPE_CHECKING:
    from app.models.evidence import Evidence
    from app.models.analysis import AnalysisJob

class DocumentType(str, enum.Enum):
    TRACK = "TRACK"
    KEYFRAME = "KEYFRAME"
    ACTIVITY_INTERVAL = "ACTIVITY_INTERVAL"
    SPATIAL_RELATION = "SPATIAL_RELATION"
    DETECTION_SUMMARY = "DETECTION_SUMMARY"

class DocumentSourceType(str, enum.Enum):
    OBSERVATION = "OBSERVATION"
    VLM_OBSERVATION = "VLM_OBSERVATION"
    SYSTEM_GENERATED = "SYSTEM_GENERATED"

class ConfidenceLevel(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class ForensicDocument(Base):
    """
    Structured, evidence-grounded record generated from Phase 1B observations.
    """
    __tablename__ = "forensic_documents"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    evidence_id: Mapped[int] = mapped_column(Integer, ForeignKey("evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    analysis_job_id: Mapped[int] = mapped_column(Integer, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False, index=True)
    
    track_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True)
    keyframe_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True)
    
    document_type: Mapped[DocumentType] = mapped_column(Enum(DocumentType), nullable=False, index=True)
    source_type: Mapped[DocumentSourceType] = mapped_column(Enum(DocumentSourceType), default=DocumentSourceType.OBSERVATION, nullable=False, index=True)
    
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    
    start_time: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    end_time: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    metadata_json: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)

    # Relationships
    embeddings: Mapped[List["EmbeddingRecord"]] = relationship("EmbeddingRecord", back_populates="forensic_document", cascade="all, delete-orphan")

class VLMObservation(Base):
    """
    Visual description generated by VLM keyframe analysis. Always stored as VLM_OBSERVATION.
    """
    __tablename__ = "vlm_observations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    evidence_id: Mapped[int] = mapped_column(Integer, ForeignKey("evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    analysis_job_id: Mapped[int] = mapped_column(Integer, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False, index=True)
    keyframe_id: Mapped[int] = mapped_column(Integer, ForeignKey("keyframes.id", ondelete="CASCADE"), nullable=False, index=True)
    
    track_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    prompt_version: Mapped[str] = mapped_column(String(50), default="1.0", nullable=False)
    
    description: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=0.85, nullable=False)
    is_safe: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)

class EmbeddingRecord(Base):
    """
    Metadata connecting ForensicDocuments to vector store entries.
    """
    __tablename__ = "embedding_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    evidence_id: Mapped[int] = mapped_column(Integer, ForeignKey("evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    analysis_job_id: Mapped[int] = mapped_column(Integer, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False, index=True)
    forensic_document_id: Mapped[int] = mapped_column(Integer, ForeignKey("forensic_documents.id", ondelete="CASCADE"), nullable=False, index=True)
    
    vector_id: Mapped[str] = mapped_column(String(128), nullable=False, unique=True, index=True)
    embedding_model: Mapped[str] = mapped_column(String(100), nullable=False)
    document_type: Mapped[str] = mapped_column(String(50), nullable=False)
    source_type: Mapped[str] = mapped_column(String(50), nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)

    forensic_document: Mapped["ForensicDocument"] = relationship("ForensicDocument", back_populates="embeddings")

class SearchQuery(Base):
    """
    Investigator natural language search log for provenance and auditability.
    """
    __tablename__ = "search_queries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    evidence_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("evidence.id", ondelete="CASCADE"), nullable=True, index=True)
    
    query_text: Mapped[str] = mapped_column(Text, nullable=False)
    extracted_intent: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    execution_time_ms: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    results: Mapped[List["SearchResult"]] = relationship("SearchResult", back_populates="search_query", cascade="all, delete-orphan")

class SearchResult(Base):
    """
    Individual evidence-grounded search result item returned for an investigator query.
    """
    __tablename__ = "search_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    search_query_id: Mapped[int] = mapped_column(Integer, ForeignKey("search_queries.id", ondelete="CASCADE"), nullable=False, index=True)
    evidence_id: Mapped[int] = mapped_column(Integer, ForeignKey("evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    
    track_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    keyframe_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    start_time: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    end_time: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    
    relevance_score: Mapped[float] = mapped_column(Float, nullable=False)
    confidence_level: Mapped[ConfidenceLevel] = mapped_column(Enum(ConfidenceLevel), default=ConfidenceLevel.HIGH, nullable=False)
    confidence_reason: Mapped[str] = mapped_column(Text, nullable=False)
    
    summary_text: Mapped[str] = mapped_column(Text, nullable=False)
    explanation_json: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    verification_status: Mapped[str] = mapped_column(String(50), default="VERIFIED", nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    search_query: Mapped["SearchQuery"] = relationship("SearchQuery", back_populates="results")

class AIModelExecution(Base):
    """
    Provenance tracking log for AI model executions (VLM, Embeddings, LLM Verification).
    """
    __tablename__ = "ai_model_executions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    evidence_id: Mapped[int] = mapped_column(Integer, ForeignKey("evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    execution_type: Mapped[str] = mapped_column(String(100), nullable=False)
    
    prompt_template: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    input_parameters: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    verification_result: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
